export const localization = {
  home: "خانه",
  products: "محصولات",
  aboutUs: "درباره ما",
  price: "قیمت",
  toman: "تومان",
  search: "جست و جو",
  adminPanel: "پنل ادمین",
  productName: "نام محصول",
  category: "دسته بندی",
  mainPage: "صفحه اصلی",
  store: "فروشگاه",
  brand: "نسکا",
};

export const pageLevelLocalization = {
  auth: {
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    password: "رمز عبور",
    phonenumber: "تلفن همراه",
    address: "آدرس",
    require: "را کامل کنید",
    minPass: "باید حداقل هشت کارکتر باشد",
    matchPass: "باید حداقل دارای یک حرف و یک عدد باشد",
    goToSignUp: "حساب کاربری ندارید ؟ ثبت نام کنید",
    goToLogin: "حساب کاربری دارید ؟ وارد شوید ",
    login: "ورود",
    signup: "ثبت نام",
    logout: "خروج",
  },
  products: {
    nonexistent: "ناموجود",
    singleProduct: {
      productImageOf: "عکس محصول شماره",
      buyer: "خریدار",
      points: "امتیاز",
      brand: "برند",
      description: "توضیحات",
      addToCart: "افزودن به سبد خرید",
      importProduct: "محصول وارداتی",
      Satisfaction: "رضایت از کالا",
      process: "عملکرد",
      strong: "عالی",
      medium: "متوسط",
      weak: "ضعیف",
      guarantee: "گارانتی و اصالت فیزیکی کالا",
      send:"امکان ارسال سریع",
      return:"سه روز ضمانت بازگشت کالا",
      original:"ضمانت اصل بودن کالا",
      support:"پشتیبانی 24 ساعته"
    },
  },
  footer: {
    links: "لینک های سریع",
    contact: "راه های ارتباطی ",
    copyRight:
      "کلیه حقوق این سایت محفوظ و متعلق به فروشگاه اینترنتی نسکا می باشد",
  },
  adminLayout: {
    menu: "منو",
    dashboard: "داشبورد",
    tables: "جدول ها",
    productData: "اطلاعات محصولات",
    productInventory: "موجودی محصولات",
    ordersStatus: "وضعیت سفارشات",
    charts: "نمودار ها",
    lineChart: "نمودار خطی",
    barChart: "نمودار میله ای",
    pieChart: "نمودار دایره ای ",
    calendar: "تقویم",
  },
};
