import { AdminLayout } from "@/components/layouts/admin/Layout";

export const localization = {
  home: "خانه",
  products: "محصولات",
  aboutUs: "درباره ما",
  price: "قیمت",
  toman: "تومان",
  search: "جست و جو",
  adminPanel: "پنل ادمین",
  productName: "نام محصول",
  category: "دسته بندی",
  subcategory:"زیر مجموعه",
  mainPage: "صفحه اصلی",
  store: "فروشگاه",
  brand: "نسکا",
};

export const pageLevelLocalization = {
  auth: {
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    password: "رمز عبور",
    phonenumber: "تلفن همراه",
    address: "آدرس",
    require: "را کامل کنید",
    minPass: "باید حداقل هشت کارکتر باشد",
    matchPass: "باید حداقل دارای یک حرف و یک عدد باشد",
    goToSignUp: "حساب کاربری ندارید ؟ ثبت نام کنید",
    goToLogin: "حساب کاربری دارید ؟ وارد شوید ",
    login: "ورود",
    signup: "ثبت نام",
    logout: "خروج",
  },
  footer: {
    links: "لینک های سریع",
    contact: "راه های ارتباطی ",
    copyRight:
      "کلیه حقوق این سایت محفوظ و متعلق به فروشگاه اینترنتی نسکا می باشد",
  },
  adminLayout:{
    menu:"منو",
    dashboard:"داشبورد",
    tables:"جدول ها",
    productData: "اطلاعات محصولات",
    productInventory : "موجودی محصولات",
    ordersStatus: "وضعیت سفارشات",
    charts:"نمودار ها",
    lineChart : "نمودار خطی",
    barChart :"نمودار میله ای",
    pieChart:"نمودار دایره ای ",
    calendar: "تقویم"
  },
  dashboard:{
    dashboard:"داشبورد",
    newOrders:"سفارشات جدید",
    profi : "سود خالص",
    totalSale: "کل فروش",
    newUser: "کاربر جدید",
    salesAmount : "میزان فروش",
    cost : "هزینه",
    income: "درآمد",
    tir : "تیر",
    mordad : "مرداد",
    statistics :"آمار بازدید",
    browsers:" مرورگر ها",
    viewers: "بازدید کنندگان"
  },
  delivary: {
    userName: "نام کاربر",
    totalPrice: "مجموع مبلغ",
    timeSubmitOrder: "زمان ثبت سفارش",
   orderStatus: "وضعیت سفارش",
    checkOrder: "بررسی سفارش",
    manageOrders: "مدیریت سفارش ها",
    pendingOrders: "سفارش های در انتظار ارسال",
    deliveredOrders: "سفارش های ارسال شده",
  },
  inventory:{
    manageInventory:"مدیریت موجودی و قیمت",
    inventory:"موجودی",
    saveChanges: "ثبت تغییرات",
    success:"بروزرسانی با موفقیت انجام شد",
    error: "خطایی در بروزرسانی محصولات رخ داده است"
  },
  productsData:{
    manageProducts:"مدیریت محصولات",
    productPhoto: "عکس محصول",
    actions: "عملیات",
    addProduct:"افزودن محصول",
    deleteTitle :"آیا از حذف محصول مطمئن هستید؟",
    deleteDescription :"این عمل غیر قابل بازگشت است و تمام اطلاعات محصول از سرور حذف خواهد شد.",
    cancel:"لغو",
    delete:"تایید حذف",
    editProduct:"ویرایش محصول",
   require: "الزامی است",
   quantity: "تعداد",
   discount:"تخفیف",
   description:"توضیحات",
   choose: "را انتخاب کنید",
   submit:"ذخیره"
  },
};
