export const localization = {
  home: "خانه",
  products: "محصولات",
  aboutUs: "درباره ما",
  price: "قیمت",
  toman: "تومان",
  search: "جست و جو",
  adminPanel: "پنل ادمین",
  productName: "نام محصول",
  category: "دسته بندی",
  subcategory: "زیر مجموعه",
  mainPage: "صفحه اصلی",
  store: "فروشگاه",
  brand: "نسکا",
};

export const pageLevelLocalization = {
  auth: {
    firstname: "نام",
    lastname: "نام خانوادگی",
    username: "نام کاربری",
    password: "رمز عبور",
    phonenumber: "تلفن همراه",
    address: "آدرس",
    require: "را کامل کنید",
    minPass: "باید حداقل هشت کارکتر باشد",
    matchPass: "باید حداقل دارای یک حرف و یک عدد باشد",
    goToSignUp: "حساب کاربری ندارید ؟ ثبت نام کنید",
    goToLogin: "حساب کاربری دارید ؟ وارد شوید ",
    login: "ورود",
    signup: "ثبت نام",
    logout: "خروج",
  },
  products: {
    nonexistent: "ناموجود",
    singleProduct: {
      productImageOf: "عکس محصول شماره",
      buyer: "خریدار",
      points: "امتیاز",
      brand: "برند",
      description: "توضیحات",
      addToCart: "افزودن به سبد خرید",
      importProduct: "محصول وارداتی",
      Satisfaction: "رضایت از کالا",
      process: "عملکرد",
      strong: "عالی",
      medium: "متوسط",
      weak: "ضعیف",
      guarantee: "گارانتی و اصالت فیزیکی کالا",
      send: "امکان ارسال سریع",
      return: "سه روز ضمانت بازگشت کالا",
      original: "ضمانت اصل بودن کالا",
      support: "پشتیبانی 24 ساعته",
      viewersComments: "امتیاز و دیدگاه کاربران",
      submitComment: "ثبت دیدگاه",
      loginFirst: "ابتدا وارد حساب کاربری خود شوید",
      loginAccount: "ورود به حساب",
      later: "بعدا",
      noComment: "دیدگاهی برای ثبت وجود ندارد",
      user: "کاربر",
      submitScore: "شما هم برای این کالا امتیاز ثبت کنید",
      scoreQuestion: "به این محصول چه امتیازی میدهید؟",
    },
  },
  footer: {
    links: "لینک های سریع",
    contact: "راه های ارتباطی ",
    copyRight:
      "کلیه حقوق این سایت محفوظ و متعلق به فروشگاه اینترنتی نسکا می باشد",
  },
  adminLayout: {
    menu: "منو",
    dashboard: "داشبورد",
    tables: "جدول ها",
    productData: "اطلاعات محصولات",
    productInventory: "موجودی محصولات",
    ordersStatus: "وضعیت سفارشات",
    addProduct: "افزودن محصولات",
    form: "فرم",
    charts: "نمودار ها",
    lineChart: "نمودار خطی",
    barChart: "نمودار میله ای",
    pieChart: "نمودار دایره ای ",
    calendar: "تقویم",
  },
  home: {
    banner: {
      nescafeTitle: "هوای خودت رو داشته باش ... ",
      nescafeDesc: "با نسکافه :)",
      starbucksTitle: { summer: "تابستون", just: "فقط" },
      starbucksDesc: {
        drink: "نوشیدنی",
        cold: "خنک",
        cool: "میچسبه",
      },
    },
    brandsDescription: {
      starbucks:
        "قهوه مورد علاقه جهان را با طیف گسترده ای از ترکیب ها و طعم ها که به طرز ماهرانه ای برای گرد هم آوردن مردم ساخته شده است، تجربه کنید.",
      nescafe:
        "روز خود را با یک تجربه قهوه غنی و روان، از برند قهوه پیشرو در جهان، با میراثی از کیفیت و نوآوری آغاز کنید.",
      fitness:
        "سبک زندگی فعال خود را با رویکردی متعادل و مغذی، از طریق طیف وسیعی از محصولات الهام گرفته از تناسب اندام ما که برای حمایت از اهداف سلامتی شما طراحی شده اند، تقویت کنید.",
    },
    mostDiscount: "پرتخفیفات",
    brands: "مجبوب ترین برند ها",
    categories: "دسته بندی ها",
    clickToSee: " برای مشاهده محصولات کلیک کنید",
  },
  dashboard: {
    dashboard: "داشبورد",
    newOrders: "سفارشات جدید",
    profi: "سود خالص",
    totalSale: "کل فروش",
    newUser: "کاربر جدید",
    salesAmount: "میزان فروش",
    cost: "هزینه",
    income: "درآمد",
    tir: "تیر",
    mordad: "مرداد",
    statistics: "آمار بازدید",
    browsers: " مرورگر ها",
    viewers: "بازدید کنندگان",
  },
  delivary: {
    userName: "نام کاربر",
    totalPrice: "مجموع مبلغ",
    timeSubmitOrder: "زمان ثبت سفارش",
    orderStatus: "وضعیت سفارش",
    checkOrder: "بررسی سفارش",
    manageOrders: "مدیریت سفارش ها",
    pendingOrders: "سفارش های در انتظار ارسال",
    deliveredOrders: "سفارش های ارسال شده",
  },
  inventory: {
    manageInventory: "مدیریت موجودی و قیمت",
    inventory: "موجودی",
    discount: " تخفیف",
    saveChanges: "ثبت تغییرات",
    success: "بروزرسانی با موفقیت انجام شد",
    error: "خطایی در بروزرسانی محصولات رخ داده است",
  },
  productsData: {
    manageProducts: "مدیریت محصولات",
    productPhoto: "عکس محصول",
    actions: "عملیات",
    addProduct: "افزودن محصول",
    deleteTitle: "آیا از حذف محصول مطمئن هستید؟",
    deleteDescription:
      "این عمل غیر قابل بازگشت است و تمام اطلاعات محصول از سرور حذف خواهد شد.",
    cancel: "لغو",
    delete: "تایید حذف",
    editProduct: "ویرایش محصول",
    success: "بروزرسانی با موفقیت انجام شد",
    successAdd: "افزودن محصول با موفقیت انجام شد",
    errorAnotherName: "نام محصول تکراری می باشد",
    require: "الزامی است",
    quantity: "تعداد",
    discount: "تخفیف",
    description: "توضیحات",
    choose: "را انتخاب کنید",
    submit: "ذخیره",
    brand: "برند",
    images: "عکس",
    productNum:"شماره"
  },
};
